System Requirements
===================

the same of Apache Pivot


Project Set-Up
==============

* Ensure that JUnit 4.x is on your classpath (for example that included with your IDE)

* Ensure you have the Scala Plugin installed and working in the IDE

* Ensure that you have the required Pivot projects (from the development trunk) in the same workspace


Building scala-use-pivot
==============

* Open the project in an IDE (for example in Eclipse), and build

